version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 5885:80
      - 5883:443
    volumes:
      - ./:/var/www/GuestBooker
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - ./:/var/www/GuestBooker
    links:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - 33069:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=guest_booker

volumes:
  db-data:
